apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 34.4.0
    helm:
      values: |
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`dashboard.docker.localhost`)  # Custom host rule
            entryPoints:
              - web  # Explicit entry point assignment
        image:
          registry: ghcr.io
          repository: traefik/traefik
          tag: v3.3.5
        metrics:
          prometheus: null
          otlp:
            enabled: true
            http:
              enabled: true
              endpoint: http://traefik-otel-collector-opentelemetry-collector.traefik.svc:4318/v1/metrics
        
        tracing:
          otlp:
            enabled: true
            http:
              enabled: true
              endpoint: http://traefik-otel-collector-opentelemetry-collector.traefik.svc:4318/v1/traces
        
        providers:
          kubernetesCRD:
            namespaces:
              - traefik
        
        globalArguments:
          - "--entrypoints.web.address=:80"  # Ensure web entrypoint exists
        
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

