---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-dashboards
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/carlosvillanua/traefik-argocd-demo.git
    targetRevision: HEAD
    path: resources/observability/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: v8.5.8
    helm:
      releaseName: traefik-grafana
      values: |
        adminPassword: topsecretpassword
        datasources:
          "datasources.yaml":
            apiVersion: 1
            datasources:
            - name: "Prometheus"
              type: "prometheus"
              url: "http://traefik-prometheus-server:80"
              access: "proxy"
              isDefault: true
            - name: "Tempo"
              type: "tempo"
              url: "http://traefik-tempo:3100"
              access: "proxy"
              isDefault: false
            - name: "Loki"
              type: "loki"
              url: "http://traefik-loki-stack:3100"
              access: "proxy"
              isDefault: false
        dashboardProviders:
          "dashboardproviders.yaml":
            "apiVersion": 1
            "providers":
            - "name": "Observability"
              "orgId": "1"
              "type": "file"
              "disableDeletion": false
              "editable": true
              "updateIntervalSeconds": 10
              "options":
                "path": "/etc/traefik-grafana/provisioning/dashboards/observability"
            - "name": "SLO"
              "orgId": "1"
              "type": "file"
              "disableDeletion": false
              "editable": true
              "updateIntervalSeconds": 10
              "options":
                "path": "/etc/traefik-grafana/provisioning/dashboards/slo"
        "extraConfigmapMounts":
        - "name": "grafana-observability-dashboards"
          "mountPath": "/etc/traefik-grafana/provisioning/dashboards/observability/dashboard.json"
          "subPath": "observability.json"
          "configMap": "grafana-dashboards-configmap"
          "readOnly": true
        - "name": "grafana-slo-dashboards"
          "mountPath": "/etc/traefik-grafana/provisioning/dashboards/slo/dashboard.json"
          "subPath": "slo.json"
          "configMap": "grafana-dashboards-configmap"
          "readOnly": true
        - "name": "traefik-opentelemetry-image-configmap"
          "subPath": "traefik-opentelemetry.png"
          "configMap": "traefik-opentelemetry-image-configmap"
          "readOnly": true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
