---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-prometheus-svc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/carlosvillanua/traefik-argocd-demo.git
    targetRevision: HEAD
    path: resources/observability/prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: v25.3.0
    helm:
      releaseName: traefik-prometheus
      values: |
        prometheus-pushgateway:
          enabled: false
        prometheus-node-exporter:
          hostRootFsMount:
            enabled: false
        server:
          global:
            scrape_interval: "15s"
            evaluation_interval: "15s"
          extraFlags:
          - 'web.enable-lifecycle'
          - 'web.enable-admin-api'
        serverFiles:
          "recording_rules.yml":
            groups:
            - name: "traefik"
              rules:
              - record: "task:http_response_error_count"
                expr: "traefik_http_requests_total{response_code=~\"5[0-9]{2}\"}"
              - record: "task:http_response_total_count"
                expr: "traefik_http_requests_total{response_code=~\"[0-9]{3}\"}"
              - record: "task:http_response_error_rate"
                expr: "sum by (job,api_name) (rate(task:http_response_error_count[1m]))"
            - name: "slo_metrics"
              rules:
              - record: "job:slo_errors_per_request:ratio_rate10m"
                expr: "sum by (job,api_name) (rate(task:http_response_error_count[10m])) / sum by (job,api_name) (rate(task:http_response_total_count[10m]))"
              - record: "job:error_budget:remaining"
                expr: "(1 - job:slo_errors_per_request:ratio_rate10m) * 100"
          "prometheus.yml":
            scrape_configs:
            - job_name: "traefik-gateway"
              static_configs:
              - targets:
                - 'opentelemetry-collector:9464'
            - job_name: otel-collector
              static_configs:
              - targets:
                - 'traefik-otel-collector-opentelemetry-collector.traefik.svc:8888'
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
