---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/traefik-workshops/traefik-argocd-demo.git
    targetRevision: HEAD
    path: resources/security/opa
  destination:
    server: https://kubernetes.default.svc
    namespace: Traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
