---
apiVersion: v1
kind: ConfigMap
metadata:
  name: no-op-oas
  namespace: tyk
data:
  no-op-oas.json: |-
    {
      "info": {
        "title": "no-op-oas",
        "version": "1.0.0"
      },
      "openapi": "3.0.3",
      "components": {
        "securitySchemes": {
          "authToken": {
            "type": "apiKey",
            "in": "header",
            "name": "Authorization"
          }
        }
      },
      "security": [
        {
          "authToken": []
        }
      ],
      "paths": {},
      "x-tyk-api-gateway": {
        "info": {
          "name": "no-op-oas",
          "state": {
            "active": true
          }
        },
        "middleware": {
          "global": {
            "trafficLogs": {
              "enabled": true
            }
          }
        },
        "server": {
          "authentication": {
            "enabled": true,
            "securitySchemes": {
              "authToken": {
                "enabled": true
              }
            }
          },
          "detailedActivityLogs": {
            "enabled": true
          },
          "detailedTracing": {
            "enabled": true
          },
          "listenPath": {
            "strip": true,
            "value": "/no-op-oas/"
          }
        },
        "upstream": {
          "url": "http://httpbingo.org"
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
  namespace: tyk
data:
  keycloak.json: |-
    {
      "info": {
        "title": "keycloak",
        "version": "1.0.0"
      },
      "openapi": "3.0.3",
      "paths": {},
      "components": {
        "securitySchemes": {
          "jwtAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT"
          }
        }
      },
      "security": [
        {
          "jwtAuth": []
        }
      ],
      "x-tyk-api-gateway": {
        "info": {
          "name": "keycloak",
          "state": {
            "active": true
          }
        },
        "middleware": {
          "global": {
            "contextVariables": {
              "enabled": true
            },
            "trafficLogs": {
              "enabled": true
            }
          }
        },
        "server": {
          "authentication": {
            "enabled": true,
            "securitySchemes": {
              "jwtAuth": {
                "header": {
                  "enabled": true,
                  "name": "Authorization"
                },
                "identityBaseField": "sub",
                "policyFieldName": "pol",
                "enabled": true,
                "defaultPolicies": [ "dHlrL25vLW9w" ],
                "scopes": {
                  "claimName": "group",
                  "scopeToPolicyMapping": [
                    {
                      "scope": "admins",
                      "policyId": "dHlrL2tleWNsb2FrLWFkbWlucw"
                    },
                    {
                      "scope": "developers",
                      "policyId": "dHlrL2tleWNsb2FrLWRldmVsb3BlcnM"
                    }
                  ]
                },
                "signingMethod": "rsa",
                "source": "aHR0cDovL2tleWNsb2FrLXNlcnZpY2UudHlrLnN2Yzo3MDAwL3JlYWxtcy9rZXljbG9hay1vYXV0aC9wcm90b2NvbC9vcGVuaWQtY29ubmVjdC9jZXJ0cw=="
              }
            }
          },
          "detailedActivityLogs": {
            "enabled": true
          },
          "detailedTracing": {
            "enabled": true
          },
          "listenPath": {
            "strip": true,
            "value": "/keycloak/"
          }
        },
        "upstream": {
          "url": "http://httpbingo.org"
        }
      }
    }
